"""add position column to badge table

Revision ID: ece8aeb2663a
Revises: 520e0f6220b6
Create Date: 2021-05-21 12:49:17.899257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece8aeb2663a'
down_revision = '520e0f6220b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('position', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'position')
    # ### end Alembic commands ###
